nginx:
  image: nginx
  volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "80:80"
    - "443:443"
  links:
    - jenkins
jenkins:
  image: jenkins
  ports:
    - "8080:8080"
